[project]
name = "fbfp"
# version = "0.0.0"
dynamic = ["version"]
requires-python = ">= 3.11"
dependencies = [
    "flask",
    "Flask-SQLAlchemy >= 3.1.1",
    "sqlalchemy[mypy] >= 2.0.0",
]

# vim: expandtab tabstop=4
